import Head from 'next/head'
import HeroSection from '../components/landing/hero'
import StatsPanel from '../components/landing/stats/StatsPanel'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection />
        <div className='mx-auto'>
          <StatsPanel />
        </div>
      </main>

    </div>
  )
}
